// <auto-generated />
using System;
using Day13Lab_Lab3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day13Lab_Lab3.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251121003543_'")]
    partial class _
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day13Lab_Lab3.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D7187AD5DA963");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F6877FBDAFDE006");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerId"));

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MajorId")
                        .HasColumnType("int")
                        .HasColumnName("MajorID");

                    b.HasKey("LearnerId")
                        .HasName("PK__Learner__67ABFCFAF2642E8B");

                    b.HasIndex("MajorId");

                    b.ToTable("Learner", (string)null);
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MajorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MajorId")
                        .HasName("PK__Major__D5B8BFB1087DC7BB");

                    b.ToTable("Major", (string)null);
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Enrollment", b =>
                {
                    b.HasOne("Day13Lab_Lab3.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Cours__5070F446");

                    b.HasOne("Day13Lab_Lab3.Models.Learner", "Learner")
                        .WithMany("Enrollments")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Learn__5165187F");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Learner", b =>
                {
                    b.HasOne("Day13Lab_Lab3.Models.Major", "Major")
                        .WithMany("Learners")
                        .HasForeignKey("MajorId")
                        .HasConstraintName("FK__Learner__MajorID__4BAC3F29");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Learner", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Day13Lab_Lab3.Models.Major", b =>
                {
                    b.Navigation("Learners");
                });
#pragma warning restore 612, 618
        }
    }
}
